### ISSUE TITLE
"This account already exists on your device"

### ISSUE THREAD

**Issue by AviFix** [kuoruan/Chromium-Android#12]
Hi,

After installing the app, when trying to login into my google account i get an error saying "this account already exists on your device".

I tested it on the following devices:
Nexus x5 running Android 8.1
Nexus 4 running Android 5.1.1
Samsung SM-J120F Running Android 5.1

All give the same error.

![photo_2018-05-04_16-57-38](https://user-images.githubusercontent.com/3835504/39631995-7d6af77a-4fbc-11e8-9946-637735a65815.jpg)

If i try login in with an account different then the one on the device then it works fine.

Thanks
Avi

**Comment by kuoruan** [comment]
This build is without Google official api key, it is not a official build, so you can't login.

https://github.com/kuoruan/Chromium-Android/blob/master/tools/args.gn#L7
