### ISSUE TITLE
generate_gradle.py 如何生成Android studio 工程

### ISSUE THREAD

**Issue by adteven** [kuoruan/Chromium-Android#15]
build/android/gradle/generate_gradle.py --output-directory out/Default --sdk AndroidStudioDefault --target //chrome/android:chrome_public_apk --canary --full --split-projects --use-gradle-process-resources
我使用的是这个命令，编译时一直报错，请问应该怎么处理

**Comment by kuoruan** [comment]
编译时报错吗？那你得先搞定编译

**Comment by adteven** [comment]
编译时正常的，也生成chromepublick.apk了，就是生成Android studio工程，然后打开工程 运行，就报错

**Comment by adteven** [comment]
我生成的时候就是 gn gen --args='target_os="android"' out/Default  然后开始编译 感谢作者，帮我看看怎么回事，发愁一周了

**Comment by kuoruan** [comment]
你把报错信息贴出来一下？

**Comment by adteven** [comment]
The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.


The targetSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.


The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.


The targetSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.


这是第一个错误，然后我改好了，还有别 d

**Comment by kuoruan** [comment]
generate_gradle.py 更新了，和我用的时候不太一样了
你别加那么多参数，先就只用
```
build/android/gradle/generate_gradle.py --output-directory out/Default --target //chrome/android:chrome_public_apk
```

**Comment by adteven** [comment]
使用你这个提示error: cannot find symbol class ChildBindingState 有一堆的多少

**Comment by adteven** [comment]
8569504我qq 我加你下，发截图跟看看，好多参数我都试过

**Comment by kuoruan** [comment]
你直接把图片拉到输入框就可以上传图片

**Comment by adteven** [comment]
![image](https://user-images.githubusercontent.com/6672364/42745024-1769ad06-8903-11e8-81bd-f52a254e4812.png)

**Comment by kuoruan** [comment]
https://github.com/kuoruan/Chromium-Android/tree/master/tools
这里是我的配置文件和源码同步脚本，但是是适用于 66 的

**Comment by adteven** [comment]
现在我要切换到66分支。就是切换到和你一样的分支，然后我生成工程，在编译一次，然后生成工程

**Comment by adteven** [comment]
你这几个我都看过的

**Comment by kuoruan** [comment]
我只是给个例子，你不一定非得用 66，就是你需要自己调整脚本来同步文件

**Comment by adteven** [comment]
我现在就想找一个能完整跑起来的版本，然后我在按照你说的那种方式去改，比如我现在编译的这个版本，直接用你的这个同步脚本，可能就不行吧

**Comment by adteven** [comment]
我现在想切换分支来编译，应该怎么做

**Comment by kuoruan** [comment]
```
git fetch --depth 5 origin +refs/tags/${tag}:$tag

git checkout "$tag"
```

**Comment by adteven** [comment]
git fetch --depth 5 origin +refs/tags/66.0.3359.155:66.0.3359.155

git checkout "66.0.3359.155"

**Comment by adteven** [comment]
gn gen --args='target_os="android"' out/Default  这个要把你args.gn里面的命令全部手动打进去吗

**Comment by kuoruan** [comment]
输出目录下有个 args.gn 文件

**Comment by adteven** [comment]
我替换了这个，然后开始编译了，稍等我在用你的同步脚本试试
