### ISSUE TITLE
Content_Shell build - help wanted

### ISSUE THREAD

**Issue by prsuhas** [kuoruan/Chromium-Android#16]
Hi,

Could you please guide me how to build content_shell_apk and import it to Android Studio, Modify custom code, Rebuild the apk ?

Any help regarding this is highly appreciated.

**Comment by kuoruan** [comment]
Sorry for replying so late. Here is the ContentShell for Android Studio.
https://github.com/kuoruan/ContentShell-Android
Not fully tested.

**Comment by prsuhas** [comment]
Hey,
Thank you so much

**Comment by prsuhas** [comment]
Hey,
Do you have the shell script to update android code from chromium source or script to generate android studio project from chromium source (Content Shell) ?

Any help regarding this regard is really appreciated.
