### ISSUE TITLE
Android 6.0及以下系统中会崩溃

### ISSUE THREAD

**Issue by oceanknowl** [kuoruan/Chromium-Android#19]
您好！非常感谢您的项目，对我的工作帮助很大！
我Clone项目后在Android Studio中编译出来的apk在7.0及以上版本中可以正常使用，但是在6.0及以下版本（API 21-23）中会崩溃（minSdkVersion = 21）。
我在googlesource上下载了完整的 66.0.3359.155 的代码，使用项目中的args.gn，编译chrome_public_apk 出来的apk可以正常在6.0及以下版本（只测试了API 21-23）中运行。
查看Logcat发现是加载libchrome.so时的Fatal Error，暂未找到更有用的其他信息。
能帮忙看看是哪里的问题吗？或者能否提供些思路来分析这个问题？多谢多谢

**Comment by kuoruan** [comment]
我测试 4.4 以上都是可以的啊

**Comment by oceanknowl** [comment]
测试了下，在项目Release里下载了apk文件，可以正常在 6.0 - 4.4 上运行。但我使用Android Studio 3.1.3 加载整个项目，然后Build apk，运行在 6.0 上会崩溃。是编译工具的问题吗，或者我缺少了某些文件？

**Comment by oceanknowl** [comment]
您好！能否告知下你那边的AS版本、Android SDK版本？我是在Ubuntu16.04中使用的最新的AS和SDK。
我这边在Android 6.0仍然会出崩溃，崩溃的Log都是：
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:gpu_process_host.cc(1368)] Unable to start gpu process, giving up.
然后会有一个load libchrome.so的错误。
怀疑是编译的问题，但却是gpu_process_host导致的崩溃，在gpu_process_host.cc中打日志发现是gpu_recent_crash_count_ >= kGpuMaxCrashCount 导致，调大kGpuMaxCrashCount后，会有一段时间不会崩溃，但无法加载网页，直到达到kGpuMaxCrashCount后直接崩溃。

**Comment by kuoruan** [comment]
你用 ```./gradlew clean build -PdisablePreDex --stacktrace``` 编译试试？
现在源码里的 AS 用的是
https://github.com/kuoruan/Chromium-Android/blob/master/build.gradle#L9

**Comment by oceanknowl** [comment]
使用 ./gradlew clean build -PdisablePreDex --stacktrace 仍然会崩溃，也是gpu_process_host.cc导致。
但是换用Mac环境，打包出来的可以运行，不会崩溃。
