### ISSUE TITLE
blink/mojom是在哪里找到的

### ISSUE THREAD

**Issue by lidachui** [kuoruan/Chromium-Android#2]
我翻源码找不到blink／mojom及其目录下的java文件
而且在out/Default目录下生成的lib.java里面也没有blink相关的jar包
请问你是怎么找到blink／mojom 和blink_public这两个内容的

**Comment by kuoruan** [comment]
我现在这里没有源码，你可以在源码目录下搜索 java 文件，肯定能找到

**Comment by lidachui** [comment]
在out/Default/lib.java/third_party/WebKit/public 下找到了相关的jar包，但是在源码中没有找到对应的哪些java文件，我把java导入依赖使用了，很谢谢，不过我还是想知道源码中能直接找到blink/mojom下的java文件么？

**Comment by kuoruan** [comment]
https://chromium.googlesource.com/chromium/src/+/master/docs/android_studio.md
导出 gradle 项目就有了。
