### ISSUE TITLE
vr问题

### ISSUE THREAD

**Issue by Loren-Wang** [kuoruan/Chromium-Android#20]
删除gradle中的vr包的时候产生了“错误: 程序包com.google.protobuf.nano不存在”，这个东西有什么解决办法吗？

**Comment by kuoruan** [comment]
https://github.com/kuoruan/Chromium-Android/blob/master/app/build.gradle#L41
你试试把这里去掉

**Comment by kuoruan** [comment]
新版通过 jar 包的方式引入了 protobuf，
```
implementation 'com.google.protobuf:protobuf-java:3.6.1'
```
应该不会存在无法找到 protobuf 了
