### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by AviFix** [kuoruan/Chromium-Android#23]
Hi,

Thank's for the great project.

I was wandering if you could please update the project to the last chromium (70?)?

Thanks
Avi

**Comment by kuoruan** [comment]
Sure, I will update this repo in 2 weeks.

**Comment by AviFix** [comment]
Great
Thanks

**Comment by kuoruan** [comment]
Updated to 70.

cbfc329fcaf0afb97be53fd613029a6d06712ef5

**Comment by AviFix** [comment]
Thank's a lot
