### ISSUE TITLE
Generate for android stuido 

### ISSUE THREAD

**Issue by DorisGM** [kuoruan/Chromium-Android#27]
请问，build/android/gradle/generate_gradle.py --output-directory out/Debug 这个要翻墙拉一些依赖吗

**Comment by kuoruan** [comment]
编译的时候就把依赖下完了，生成 android 项目的时候不需要额外依赖。

**Comment by DorisGM** [comment]
> 编译的时候就把依赖下完了，生成 android 项目的时候不需要额外依赖。

还有一个问题，你用android_studio.md导出gradler工程的时候，电脑配置是16g内存还是8个的呢？ 我执行这个build/android/gradle/generate_gradle.py --output-directory out/Debug 命令去生成android项目 电脑配置是8G 内存，发现很卡，卡到动不了。

**Comment by kuoruan** [comment]
我用虚拟机，4G加8G虚拟内存就行了，不存在卡的问题

**Comment by DorisGM** [comment]
> 我用虚拟机，4G加8G虚拟内存就行了，不存在卡的问题

那大神，讲道理我8G内存是不是不应该卡？ 有没有可能是别的原因。 可以指点一下吗

**Comment by DorisGM** [comment]
![ks4o 0 8 9 8 o1i 2uw8vf](https://user-images.githubusercontent.com/22267767/49138947-88427480-f32b-11e8-84b5-e5e583c4dfe3.png)这是我现在的内存情况，820978076 能够加个qq请教一下。

**Comment by kuoruan** [comment]
你这内存是绝对够用的，你在编译卡住的时候看看 free 和 top

**Comment by DorisGM** [comment]
> 你这内存是绝对够用的，你在编译卡住的时候看看 free 和 top

卡到电脑难以动弹 (*/ω＼*)   我再试一次

**Comment by DorisGM** [comment]
> 你这内存是绝对够用的，你在编译卡住的时候看看 free 和 top
再次尝试之后还是在
![bd jag80oun5efk sweffjy](https://user-images.githubusercontent.com/22267767/49264953-46c8db00-f48b-11e8-9ae8-de1993af881c.png) 这一步卡主进行不了下一步，请问你当时生成gradler快不快。 有没有可能是我前面编译中遗漏了什么、对Ubuntu系统以及pyhthon git的版本有没有特别要求。 再次请教！

**Comment by kuoruan** [comment]
你确定你先按 
https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md
这个教程编译出了 APK 文件？

**Comment by DorisGM** [comment]
> 你确定你先按
> https://chromium.googlesource.com/chromium/src/+/master/docs/android_build_instructions.md
> 这个教程编译出了 APK 文件？

![image](https://user-images.githubusercontent.com/22267767/49266060-ade88e80-f48f-11e8-8b37-17cae7ed87e9.png)
嗯 执行到了这一步，下面的不是必须的吧？
![image](https://user-images.githubusercontent.com/22267767/49266105-ce184d80-f48f-11e8-8834-b9325afc39db.png)
![image](https://user-images.githubusercontent.com/22267767/49266110-d2dd0180-f48f-11e8-9fd4-ae0ad8730d59.png)
 正常要导出多久？

**Comment by kuoruan** [comment]
```
build/android/gradle/generate_gradle.py --output-directory out/Default --target //chrome/android:chrome_public_apk
```
把 target 加上

**Comment by DorisGM** [comment]
> ```
> build/android/gradle/generate_gradle.py --output-directory out/Default --target //chrome/android:chrome_public_apk
> ```
> 把 target 加上

加上了 这个是指定了只导出我当前public apk的工程吗？

**Comment by kuoruan** [comment]
你只编译了chrome_public_apk，导出gradle项目的时候就指定一下target，防止它生成其他不需要的东西

**Comment by DorisGM** [comment]
> 你只编译了chrome_public_apk，导出gradle项目的时候就指定一下target，防止它生成其他不需要的东西

嗦嘎。谢谢大神。看起来似乎顺利了

**Comment by DorisGM** [comment]
首先感谢大神之前的指导， 我现在将工程导入到AndroidStudio 尝试直接运行，运行过程中缺什么补什么，但是出现了
![image](https://user-images.githubusercontent.com/22267767/49503201-df0ef780-f8b1-11e8-8fe5-5d98549f9eac.png)
android.os库找不到。 都可以跳转怎么会找不到呢。是否有遇到过、 先谢过

**Comment by DorisGM** [comment]
> 貌似遇到过，这个是抽风了，把项目clean一下，重新打开

请问 我想编一个一个旧版本的apk 是否直接在项目代码目录中，不想重新checkout 一份，通过git reset --hard 回溯到某个版本。然后编译，请问可以这样做吗 ，因为我这样做之后，有些build文件不对 我就执行了 gclient sync和gclient runhooks 以及重新下载build依赖。

**Comment by kuoruan** [comment]
```
git fetch --depth 5 origin +refs/tags/${tag}:${tag}
git checkout ${tag}
```

```${tag}``` 是任意版本号

**Comment by DorisGM** [comment]
> ```
> git fetch --depth 5 origin +refs/tags/${tag}:${tag}
> git checkout ${tag}
> ```
> `${tag}` 是任意版本号
![image](https://user-images.githubusercontent.com/22267767/49504156-18486700-f8b4-11e8-983c-f035ec4ba31a.png)

然后再执行 这两条就可以了？ 因为我想换个目录。 谢谢

**Comment by kuoruan** [comment]
```
gclient sync
```

不能少，然后再编译就行了

**Comment by DorisGM** [comment]
> ```
> gclient sync
> ```
> 不能少，然后再编译就行了

好的，再次感谢
