### ISSUE TITLE
70版播放视频出错

### ISSUE THREAD

**Issue by Z-P-J** [kuoruan/Chromium-Android#28]
两个70版播放视频时直接出现崩溃页面，66版没问题。请问一下这是什么情况？

**Comment by Pauliu** [comment]
还是有这个问题， 我用你的build 设置在Ubuntu下编译完成， 在墙内视频网站直接crash，， 还不是直接用的你转好的代码，，只用了target_os = "android" target_cpu = "arm64" 这个参数， 页面没crash，提示播放错误， 可能和视频编码解码有关。

**Comment by kuoruan** [comment]
Updated.
