### ISSUE TITLE
generate_gradle.py具体命令是怎么样的呢

### ISSUE THREAD

**Issue by zmyxingyu** [kuoruan/Chromium-Android#3]
最近网络管的严格，看不到官方文档，想问下命令具体参数是什么，注意事项有没有？

**Comment by kuoruan** [comment]
```
build/android/gradle/generate_gradle.py --canary --output-directory out/Release
```
```out/Release``` 是编译输出目录
当前只有 63 以上版本支持 --canary 参数，来输出支持 Android Studio 3.0 的代码

**Comment by zmyxingyu** [comment]
报no such file or directory :'../out/Release/build_vars.txt'  是不是要新建一个build_vars.txt，加一些配置信息

**Comment by kuoruan** [comment]
```out/Release``` 这个目录是你已经编译过 chrome_public_apk 的生成目录，gradle 的文件会生成到 ```out/Release/gradle```

**Comment by zmyxingyu** [comment]
utput-directory out/Default
W    0.000s Main  Creating project at: /home/shud/Documents/chromium/src/out/Default/gradle
W    0.001s Main  Building .build_config files...
Traceback (most recent call last):
  File "build/android/gradle/generate_gradle.py", line 801, in <module>
    main()
  File "build/android/gradle/generate_gradle.py", line 733, in main
    _RunNinja(output_dir, [e.NinjaBuildConfigTarget() for e in main_entries])
  File "build/android/gradle/generate_gradle.py", line 107, in _RunNinja
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

报错信息

**Comment by kuoruan** [comment]
https://beijing.source.codeaurora.org/mirrors/chromium.googlesource.com/chromium/src/tree/docs/android_build_instructions.md?h=63.0.3239.27

https://beijing.source.codeaurora.org/mirrors/chromium.googlesource.com/chromium/src/tree/docs/android_studio.md?h=63.0.3239.27

**Comment by zmyxingyu** [comment]
我想请问下，你是用的上面代理拿的代码，还是直接翻墙拿的google代码，走通整个流程的

**Comment by zmyxingyu** [comment]
我这边之前是翻墙拿fetch chromium  60版本的代码，可以编译出apk，但后面脚本一直报错，各种文件找不到，在编译目录页没有； 看文档是要 fetch android  不知道跟这个有关系没

**Comment by zmyxingyu** [comment]
具体是文件找不到
    0.000s Main  Creating project at: /home/shud/Documents/chromium/src/out/my_out/gradle
W    0.001s Main  Building .build_config files...
W    0.001s Main  Running: ['ninja', '-C', '/home/shud/Documents/chromium/src/out/my_out', '-j1000', 'android_webview/test:webview_instrumentation_apk__build_config', 'android_webview/test:webview_instrumentation_test_apk__apk__build_config', 'base:base_junit_tests__java_binary__build_config', 'chrome/android:chrome_junit_tests__java_binary__build_config', 'chrome/android:chrome_public_apk__build_config', 'chrome/android:chrome_public_test_apk__apk__build_config', 'chrome/android:chrome_sync_shell_apk__build_config', 'chrome/android:chrome_sync_shell_test_apk__apk__build_config', 'content/public/android:content_junit_tests__java_binary__build_config', 'content/shell/android:content_shell_apk__build_config']
Traceback (most recent call last):
  File "build/android/gradle/generate_gradle.py", line 801, in <module>
    main()
不知道是哪里出了问题

**Comment by kuoruan** [comment]
我这个是直接拿的官方的源码，确保 ```gclient sync``` 成功运行，然后你可以试试用我的编译参数
https://github.com/kuoruan/Chromium-Android/blob/master/Chromium/args.gn
其他都是一些小问题

**Comment by zmyxingyu** [comment]
我是用了这个args.gn  编译也成功了 ，就是 运行 build/android/gradle/generate_gradle.py --output-directory out/Release  报上面的错误，这个就尴尬了

**Comment by kuoruan** [comment]
你可以试试重新下载一个版本的源码

**Comment by kuoruan** [comment]
```
git fetch --depth 10 origin +refs/tags/63.0.3239.30:63.0.3239.30
gclient sync
```
63.0.3239.30 是任意版本号

**Comment by zmyxingyu** [comment]
在这个工程上包装webview,类似腾讯x5内核，才方便使用，不知道你研究过没

**Comment by kuoruan** [comment]
Chrome 的内核文件就 46M 左右，而源码中可以编译出 webview，但是也有这么大，这适合于用来做自定义浏览器。而提取的话，我没有细看，估计需要先吧 org.chromium.base.library_loader 提取出来
