### ISSUE TITLE
libchrome.so 与 libchrome.cr.so 的区别

### ISSUE THREAD

**Issue by DorisGM** [kuoruan/Chromium-Android#31]
你好。官方的out目录里面是libchrome.cr.so文件，请问你目录里面的libchrome.so文件是怎么生成的。 还有如果我要修改c的代码，然后重新编译so库，要怎么做？谢谢。

**Comment by DorisGM** [comment]
> [args.gn](https://github.com/kuoruan/Chromium-Android/blob/master/tools/args.gn)
> Use this args to build chrome_public_apk
![image](https://user-images.githubusercontent.com/22267767/49627156-3cbd5400-fa18-11e8-931b-5f618b0667a1.png)

这个需要清空之前的编译的out/default目录重新编吗？ 还是我直接执行gn 命令到原来的目录，然后重新编就可以生效？ 我没有清空，直接重新执行这两个命令， 在out/Default里面还是没找到libchrome.so

**Comment by AviFix** [comment]
> [args.gn](https://github.com/kuoruan/Chromium-Android/blob/master/tools/args.gn)
> Use this args to build chrome_public_apk

Hi,
Could you please show an example of  the build command  with these args ?

Thanks

**Comment by kuoruan** [comment]
There is a args.gn file in you build dir, replace it.

**Comment by vaprocs** [comment]
so, what is the diff between .cr.so with .so? @kuoruan
