### ISSUE TITLE
GoogleAPIKeys.java 文件哪里找到的？ 请教是否知道谷歌账号如何同步？

### ISSUE THREAD

**Issue by DorisGM** [kuoruan/Chromium-Android#37]
![image](https://user-images.githubusercontent.com/22267767/50410322-31995f00-0833-11e9-9834-cedca78ee686.png)
我编译之后再这两个路径没找到，这是我的args.gn 文件内容、
![image](https://user-images.githubusercontent.com/22267767/50410350-58f02c00-0833-11e9-85ef-62bf56f81645.png)
 谢谢。

**Comment by DorisGM** [comment]
还有一个问题 ，我改了args.gn 之后 先执行了 
![image](https://user-images.githubusercontent.com/22267767/50410520-6954d680-0834-11e9-8cc2-2566200e77a2.png) 这个过程， 修改的gn 参数是否就已经生效了？ 还是要重新build 一个新的out/new 才生效呢

**Comment by kuoruan** [comment]
1. 请在你的源码文件夹里边搜索对应文件。

2. 配置文件改了，可以先 ```ninja -C out/Release -t clean``` 再编译。

**Comment by DorisGM** [comment]
1.搜索了找不到那个文件，我的配置好像生成不了那个文件。
2.好的谢谢

**Comment by kuoruan** [comment]
请先执行该操作：

https://chromium.googlesource.com/chromium/src/+/master/docs/android_studio.md
