### ISSUE TITLE
Url not load in webview

### ISSUE THREAD

**Issue by ghost** [kuoruan/Chromium-Android#39]
Hi,
   when i add webview and load url then content not load. how to fix this? please help me,

**Comment by kuoruan** [comment]
Updated.

**Comment by ghost** [comment]
i can't update project so can you please tell me how to resolve this issue?
*Regards,*
*Devilal Tank*
*M: +91 9601535002*

**Comment by ghost** [comment]
hey can you please tell me how to solve this problem?

**Comment by kuoruan** [comment]
New version works well on my device.
