### ISSUE TITLE
[Question] How to always keep the fullscreen mode?

### ISSUE THREAD

**Issue by nickcartery** [kuoruan/Chromium-Android#8]
Hi,

Im creating a fullscreen app, but Chromium's UI has an URL bar, I dont know how to hide it everytime.
I found this function to enter the fullscreen mode, but cannot keep it, It will be go to exit if navigating to a new URL

> getFullscreenManager().setPersistentFullscreenMode(true);

Also have another issue: How to turn off the red border? Like this image: http://cdn.droidviews.com/wp-content/uploads/2013/06/Fix-the-Red-Frame-Android.jpg . But only get issue with Chromium

Thanks!

**Comment by kuoruan** [comment]
For the first question. I am not familiar with the source code, so I can't help you. Maybe you can head to https://groups.google.com/a/chromium.org/d/forum/chromium-dev to get some help.

About the red frame. I find a solution at https://github.com/brave/browser-android-tabs/issues/321.
I will make a new build with the flag ```android_channel = "stable"``` later.

**Comment by nickcartery** [comment]
Can you please enable autoplay? Or can you tell me how to enable it by default?
I mean the flag: autoplay-policy
